name: gRPC queries tests

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - src/
    - tests.sh
    - .github/workflows/grpc_tests.yml

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      SF_API_TOKEN: ${{ secrets.SF_API_TOKEN }}
      BLOCKTIME_GITHUB_TOKEN: ${{ secrets.BLOCKTIME_GITHUB_TOKEN }}
    steps:
      - uses: actions/setup-go@v4
      - uses: actions/checkout@v3
      
      - name: Install grpcurl
        run: go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest

      - name: Install WasmEdge library
        run: |
          curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | sudo bash -s -- -p /usr/local

      - name: Install substreams-sink-kv
        run: |
          git config --global url."https://${BLOCKTIME_GITHUB_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          cd $GOPATH
          mkdir -p src/github.com/substreams-sink-kv
          cd src/github.com/substreams-sink-kv
          git clone https://github.com/streamingfast/substreams-sink-kv.git
          cd substreams-sink-kv
          go get github.com/second-state/WasmEdge-go/wasmedge@latest
          cd cmd/substreams-sink-kv
          go install
      
      - name: substreams-sink-kv version check
        run: |
          substreams-sink-kv -v
          substreams-sink-kv -h

      - name: Running tests
        run: |
          export SUBSTREAMS_API_TOKEN=$(curl https://auth.streamingfast.io/v1/auth/issue -s --data-binary '{"api_key":"'$SF_API_TOKEN'"}' | jq -r .token)
          cd /home/runner/work/blocktime-service/blocktime-service
          ./tests.sh
    
